version: '2.1'

networks:
  isolation-network:
    driver: bridge

services:
# ======================  USER SERVICE ====================
  users-service:
    container_name: users-service
    build: ./services/server/
    volumes:
      - './services/users:/usr/src/app'
      - './services/users/package.json:/usr/src/package.json'
    ports:
      - '3000:3000' # expose ports - HOST:CONTAINER
    networks:
      - isolation-network
# ======================  WEB SERVICE ====================
  web-service:
    container_name: web-service
    build: ./services/web/
    volumes:
      - './services/web:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - '4000:4000' # expose ports - HOST:CONTAINER
    depends_on:
      users-service:
        condition: service_started
    networks:
      - isolation-network
# ======================  X SERVICE ====================